### ISSUE TITLE
add 1D example[s]

### ISSUE THREAD

**Issue by JeffreySarnoff** [bionanoimaging/IndexFunArrays.jl#9]
Assuming this works with 1D arrays, it would help to have an example for a windowed mean over a vector and one other 1D windowing example in the docs.

**Comment by roflmaostc** [comment]
Hey,

I agree the docs are not in the best shape.
I'm not totally sure what you are referring to with "windowed mean"

Regarding a 1D window:
```julia
julia> window_gaussian((9,), border_in=(0.0,), border_out=(1.0,))
9-element IndexFunArray{Float64, 1, IndexFunArrays.var"#325#327"{Float64, Tuple{Int64}, Tuple{Float64}, Tuple{Float64}, Tuple{Float64}}}:
 0.20592424643419874
 0.41111229050718745
 0.6736384553447268
 0.9059551911095096
 1.0
 0.9059551911095096
 0.6736384553447268
 0.41111229050718745
 0.20592424643419874
```

**Comment by RainerHeintzmann** [comment]
... for the mean, you may want to use the normalized version of the Gausian.

**Comment by RainerHeintzmann** [comment]
> Assuming this works with 1D arrays, it would help to have an example for a windowed mean over a vector and one other 1D windowing example in the docs.

Do you mean a mean-filtering or just calculating the mean of an array that is multiplied with the window (going to zero).
Or do you mean a windowed mean in the sense that only the weights of the averaging change near the border according to a window function?
The latter would be this:
```julia
julia> arr = rand(1000);
       sum(window_hanning(arr) .* arr) ./ sum(window_hanning(size(arr)))
0.49932014498905136
```
